<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_img altAuthenticate with Email srcSetsign_72abec</name>
   <tag></tag>
   <elementGuidId>ac8edb84-2c77-4121-8fe4-22e6777f8d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='signUpWithEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signUpWithEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8657cb7-c2bb-4087-9ebf-ec9eab74f511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signUpWithEmail</value>
      <webElementGuid>f9db3006-411a-4eac-bb96-04018854336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>230dff19-4bca-4b55-b708-e6dfcbc2fa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Authenticate with Email</value>
      <webElementGuid>a530b98d-0032-4d77-97a0-de5c32eae4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;img alt=&quot;Authenticate with Email&quot; srcSet=&quot;/sign-up/email.svg 1x, /sign-up/email.svg 2x&quot; src=&quot;/sign-up/email.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Sign up with email</value>
      <webElementGuid>c18f779e-534b-41ff-86c2-5e9c36c5f107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signUpWithEmail&quot;)</value>
      <webElementGuid>d7f53e51-1ac7-456c-af7a-91e41f54517a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='signUpWithEmail']</value>
      <webElementGuid>99397af2-afb1-42c5-94a6-4a536940d9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>d1cd4bdc-10f5-48d2-92b4-b66c3c53722f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'register')]</value>
      <webElementGuid>f2e54834-b690-45d4-afab-63b718b6fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>09f48044-1d10-48e3-a9ab-61ac182ee380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'signUpWithEmail' and @href = 'register' and @title = 'Authenticate with Email' and (text() = '&lt;img alt=&quot;Authenticate with Email&quot; srcSet=&quot;/sign-up/email.svg 1x, /sign-up/email.svg 2x&quot; src=&quot;/sign-up/email.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Sign up with email' or . = '&lt;img alt=&quot;Authenticate with Email&quot; srcSet=&quot;/sign-up/email.svg 1x, /sign-up/email.svg 2x&quot; src=&quot;/sign-up/email.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Sign up with email')]</value>
      <webElementGuid>191de14e-2e0d-48f3-bab7-4811564e07d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
