<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Not a valid email format</name>
   <tag></tag>
   <elementGuidId>2124ad5b-fa5c-4333-b231-6123fd16af95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='email-error-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-error-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9b8dd484-dc0b-4474-a4e4-808e38fdd3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-error-message</value>
      <webElementGuid>12f43a6c-2538-4ae8-b7db-c10974ab40f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInputGroup_error-message__tMFB0</value>
      <webElementGuid>aa9c7958-baed-4c2c-a4aa-76f405818175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not a valid email format</value>
      <webElementGuid>9e2adc04-fea3-4fbc-9f5e-c3d9982ff001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-error-message&quot;)</value>
      <webElementGuid>87b31977-ec4a-4302-8885-3dcfdca96ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='email-error-message']</value>
      <webElementGuid>44a2e87e-c6ec-4d07-8f5f-6b1b3d92add6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/form/div/p</value>
      <webElementGuid>3042a898-6307-4b15-b4d7-d9fcc8a4c598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>d836dd0d-ecb7-4db9-b2fb-4fe885537b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'email-error-message' and (text() = 'Not a valid email format' or . = 'Not a valid email format')]</value>
      <webElementGuid>c01f8c88-195d-49a2-93a3-d94a18aa28c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
